# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mozzy < Formula
  desc "Modern HTTP client for the terminal - a Postman alternative for JSON APIs"
  homepage "https://humancto.github.io/homebrew-mozzy/"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/humancto/mozzy/releases/download/v2.0.1/mozzy_2.0.1_macos_amd64.tar.gz"
      sha256 "6234c5637490366e190ab96859f3f9ec659b2be8a3ad90e29272db064d40cd43"

      def install
        bin.install "mozzy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/humancto/mozzy/releases/download/v2.0.1/mozzy_2.0.1_macos_arm64.tar.gz"
      sha256 "f4f82128721f5efbe4012cfaa96e0cd00b8c03f218017d41917716c15ea07d15"

      def install
        bin.install "mozzy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/humancto/mozzy/releases/download/v2.0.1/mozzy_2.0.1_linux_amd64.tar.gz"
      sha256 "346c42884d46de21b6e83ee6b2e2b72b6c43fa69b6e56a88a56c4816542e74f8"
      def install
        bin.install "mozzy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/humancto/mozzy/releases/download/v2.0.1/mozzy_2.0.1_linux_arm64.tar.gz"
      sha256 "cf321eeaedacd446bd99f1878beea68cc4d9b3714d7a60074d1ee26bb9875d72"
      def install
        bin.install "mozzy"
      end
    end
  end

  test do
    system "#{bin}/mozzy", "--version"
  end
end
