# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mozzy < Formula
  desc "Modern HTTP client for the terminal - a Postman alternative for JSON APIs"
  homepage "https://humancto.github.io/homebrew-mozzy/"
  version "2.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/humancto/homebrew-mozzy/releases/download/v2.0.1/mozzy_2.0.1_macos_amd64.tar.gz"
      sha256 "13e9eb939fccf00bed58f86dbc2bb02a2b4b98417b567efa82eea26452dd136d"

      def install
        bin.install "mozzy"
      end
    end
    on_arm do
      url "https://github.com/humancto/homebrew-mozzy/releases/download/v2.0.1/mozzy_2.0.1_macos_arm64.tar.gz"
      sha256 "4491f7540f5a246b84a8413909a0ff92c0696578c3a9721aa7435f75d5d5249f"

      def install
        bin.install "mozzy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humancto/homebrew-mozzy/releases/download/v2.0.1/mozzy_2.0.1_linux_amd64.tar.gz"
        sha256 "09f47beeeb1518f54c3eb6705b7c9581e931c0f999f94b92d4f922396eeee639"

        def install
          bin.install "mozzy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/humancto/homebrew-mozzy/releases/download/v2.0.1/mozzy_2.0.1_linux_arm64.tar.gz"
        sha256 "b71b1621d1353dcb3d1845b30dac274156485dc04100e6c3bff664c63fd3d22f"

        def install
          bin.install "mozzy"
        end
      end
    end
  end

  test do
    system "#{bin}/mozzy", "--version"
  end
end
